title: Alex Martinez Savournin
logo: "/images/logo.png?raw=true"

description: > 
  Software Engineering student (Level II) at McMaster University.
  <br><br>
  Interested in AI-assisted development, game and graphics programming, and backend systems.
  <br><br>
  Email: <a href="mailto:alexmartsavournin@gmail.com">alexmartsavournin@gmail.com</a>
  <br>
  GitHub: <a href="https://github.com/alephnull1678">github.com/alephnull1678</a>
  <br>
  LinkedIn: <a href="http://www.linkedin.com/in/alex-martinez-9aba55367">http://www.linkedin.com/in/alex-martinez-9aba55367</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics: UA-000000-0 # your Google Analytics tracking ID here (or remove line if not needed)
